package com.seeth.exception.models;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum AppErrorCode {

    //common error codes
	LOGIN_REQUIRED						("LOGIN_REQUIRED"),
	
	USER_ROLES_REQUIRED					("USER_ROLES_REQUIRED"),
	
	INSUFFICIENT_PRIVILEGES				("INSUFFICIENT_PRIVILEGES"),
	UNAUTHORISED_ACCESS					("UNAUTHORISED_ACCESS"),
	UNAUTHORISED_ROLE_ACCESS			("UNAUTHORISED_ROLE_ACCESS"),
	UNAUTHORISED_CONSULTANCY_ACCESS		("UNAUTHORISED_CONSULTANCY_ACCESS"),
	
    DATA_NOT_SAVED						("ERROR_WHILE_SAVING_DATA"),
    
    USER_ALREADY_EXISTS					("USER_ALREADY_EXISTS"),
    CAREER_PROFILE_ALREADY_EXISTS		("CAREER_PROFILE_ALREADY_EXISTS"),
    
    USER_NOT_FOUND						("USER_NOT_FOUND"),
    ROLE_NOT_FOUND						("ROLE_NOT_FOUND"),
    IMAGE_NOT_SAVED						("IMAGE_NOT_SAVED"),
    USER_SKILL_NOT_FOUND				("USER_SKILL_NOT_FOUND"),
    USER_CAREER_PROFILE_NOT_FOUND		("USER_CAREER_PROFILE_NOT_FOUND"),
    USER_EXPERIENCES_NOT_FOUND			("USER_EXPERIENCES_NOT_FOUND"),
    USER_PROJECTS_NOT_FOUND				("USER_PROJECTS_NOT_FOUND"),
    USER_ACHIEVEMENTS_NOT_FOUND			("USER_ACHIEVEMENTS_NOT_FOUND"),
    USER_DOCUMENT_NOT_FOUND				("USER_DOCUMENT_NOT_FOUND"),
    CONSULTANCY_NOT_FOUND				("CONSULTANCY_NOT_FOUND"),
    JOB_POSTING_NOT_FOUND				("JOB_POSTING_NOT_FOUND"),
    ADDRESS_NOT_FOUND					("ADDRESS_NOT_FOUNG"),
    USER_ACADEMIC_DETAILS_NOT_FOUND		("USER_ACADEMIC_DETAILS_NOT_FOUND"),
    
    MODEL_CONVERSION_ERROR				("MODEL_CONVERSION_ERROR"),
    ENTITY_CONVERSION_ERROR				("ENTITY_CONVERSION_ERROR"),
    INVALID_INPUT_DATA					("INVALID_INPUT_DATA"),
    INTERNAL_SERVER_ERROR				("INTERNAL_SERVER_ERROR"),
    
    JOB_ALREADY_APPLIED					("ACTIVE_JOB_APPLICATION_EXISTS");

    private final String key;
}